name: Canary Release

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [master]

jobs:
  canary-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            **/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install
        working-directory: packages/aicommit

      - name: Build
        run: bun run build
        working-directory: packages/aicommit

      - name: Publish canary version
        working-directory: packages/aicommit
        run: |
          current_version=$(node -p "require('./package.json').version")
          latest_canary=$(npm view @kkidd/aicommit dist-tags.canary)
          if [[ $latest_canary == *"$current_version"* ]]; then
            next_version=$(npx semver $latest_canary -i prerelease)
          else
            next_version="$current_version-canary.0"
          fi
          echo "Publishing version $next_version"
          npm version $next_version --no-git-tag-version --allow-same-version
          npm publish --tag canary --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}