name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun
          **/node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun test

    - name: Run linter
      run: bun run lint

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun
          **/node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install

    - name: Build
      run: bun run build
    
    - name: Upload aicommit package build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aicommit-dist
        path: packages/aicommit/out
      
  prerelease:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Download aicommit build artifacts
      uses: actions/download-artifact@v3
      with:
        name: aicommit-dist
        path: packages/aicommit/out
  
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun
          **/node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Bump version and publish
      working-directory: packages/aicommit
      run: |
        bun run release:canary
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Push changes
      run: git push --follow-tags
